branch-defaults:
  master:
    environment: appatouch-dev
    group_suffix: null
global:
  application_name: appatouch
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  profile: null
  sc: git
